### ISSUE TITLE
アクションが呼ばれるタイミング

### ISSUE THREAD

**Issue by uchan-nos** [cybozu-go/goma#4]
> The monitor kicks actions for recovery when the probe or filtered result of the probe reports recovery from failures.

probe が報告する数値が max を超えた場合にアクションが呼ばれるものだと思っていたのですが、上記の記述を読むと max を下回ったとき（= when the probe or filtered result of the probe reports recovery from failures）に呼ばれるのでしょうか？

**Comment by ymmt2005** [comment]
I cannot understand your question.
Note that actions have several types including on failure and on recovery.

**Comment by ymmt2005** [comment]
and `min` and `max` define the range of probe values that are considered normal (no failure).
On failure action is invoked when the monitor observes probe value goes out of the range,
and on recovery action is invoked when the monitor observes probe value return to the range
(from outside, of course).
